# Generated by Django 2.2.6 on 2019-10-11 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20191011_1934'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='products',
            index_together={('id', 'slug', 'category', 'subcategory')},
        ),
    ]
