# Generated by Django 2.2.6 on 2019-10-11 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20191011_2015'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='products',
            index_together=set(),
        ),
    ]
